### PR TITLE
Added headless selection API

### PR DESCRIPTION
**Pull request by thegecko**
@jyasskin @mikaelkindborg 

This PR addresses #10 by extending ```requestDevice()``` and adding a ```cancelRequest()``` as discussed in the issue:

```js
bluetooth.requestDevice({
    filters:[{ services:[ "heart_rate" ] }],
    // adding this function causes the Promise to resolve on timeout with no device, not reject
    deviceFound: function(bluetoothDevice) {
        addDeviceToList(bluetoothDevice);
        // for synchronous requirements returning true here can stop scanning and
        // resolve Promise of requestDevice() with current bluetoothDevice
    }
})
.then(...

var bluetoothDevices = [];
function addDeviceToList(bluetoothDevice) {
    bluetoothDevices.push(bluetoothDevice);
    // display found devices to the user
}

// event when user chooses a device
function handleUserSelect(index) {
    var bluetoothDevice = bluetoothDevices[index];

    // 'cancelRequest()' stops scanning and returns a promise
    bluetooth.cancelRequest()
    .then(() => {
        return bluetoothDevice.gatt.connect();
    })
    ...
}
```

The PR includes two new node examples showing continuous ```eddystone``` scanning and realtime command-line selection of a device.

What are your thoughts?

### CODE REVIEW

**Comment by mikaelkindborg** [comment]
@thegecko Looking forward to experimenting with this!

**Comment by mikaelkindborg** [comment]
@thegecko Very cool with the Eddystone example!

I don't get how/when .then(scan) is called. (I have not really got the hang on when .then is called in general, how it can be called without resolving any promise. Will study the code a bot more!)

**Comment by thegecko** [comment]
@mikaelkindborg It's just a recursion

**Comment by thegecko** [comment]
@beaufortfrancois @scheib @g-ortuno You may be interested in this headless Web Bluetooth "extension"

**Comment by mikaelkindborg** [comment]
@thegecko Looked further at api-web-bluetooth.js and now better understand how the Eddystone example works! My understanding is that in the Eddystone example, .then(scan) will never be called, since handleDeviceFound does not return a truthy value or call cancelRequest. Is this correct?

**Comment by thegecko** [comment]
```.then(scan)``` does get called recursively once the scan timeout completes.

The ```requestDevice()``` call resolves instead of rejecting because a deviceFound function has been specified.

**Comment by mikaelkindborg** [comment]
@thegecko Oh, I didn't consider the scan timeout! Thanks for clarifying this.

**Comment by beaufortfrancois** [comment]
It is interesting! Will definitely look at this when addressing https://github.com/WebBluetoothCG/web-bluetooth/issues/191

**Pull request merged**
